version: '3.4'

services:
  webapp:
    image: my-webserver
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    depends_on:
      - db

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql-server
    container_name: my-mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql    
    environment:          
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: customers

  adminer:
    image: adminer
    container_name: my-adminer
    restart: always
    ports:
      - 8084:8080

  jenkins:
    image: jenkins/jenkins
    ports:
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home

volumes:
    data-volume: